import { OrderStatus } from '../types';

export const CUSTOMER_SECTIONS = {
  en: {
    common: {
      currencyCode: 'SAR',
      pleaseSignIn: 'Please sign in to continue.',
      loading: 'Loading...',
      browseMedicines: 'Browse Medicines',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      remove: 'Remove',
      delete: 'Delete',
      add: 'Add',
      confirm: 'Confirm',
      setDefault: 'Set as Default',
      notProvided: 'Not provided',
    },
    profile: {
      eyebrow: 'Account Center',
      title: 'My Profile',
      subtitle: 'Manage your personal information and account preferences securely.',
      email: 'Email Address',
      phone: 'Phone Number',
      role: 'Account Role',
      roleTitle: 'Access Permissions',
      roleDescription: 'Your role determines which areas and data you can access. Role changes can only be made by administrators.',
      signOut: 'Sign Out',
      signingOut: 'Signing Out...',
      signedOut: 'Signed out successfully.',
      signOutError: 'Failed to sign out.',
      editProfile: 'Edit Profile',
      fullName: 'Full Name',
      saveChanges: 'Save Changes',
      profileUpdated: 'Profile updated successfully.',
      updateError: 'Failed to update profile.',
      loginRequired: 'Please sign in to view your profile.',
      userId: 'User ID',
      roleLabels: {
        admin: 'Administrator',
        pharmacist: 'Pharmacist',
        customer: 'Customer',
      },
    },
    saved: {
      eyebrow: 'Quick Access',
      title: 'Saved Medicines',
      subtitleOne: 'medicine saved for quick access',
      subtitleMany: 'medicines saved for quick access',
      emptyTitle: 'No saved medicines yet',
      emptyMessage: 'Save medicines to reach them faster later.',
      dosageFallback: 'Medicine',
      strength: 'Strength',
      bestAvailablePrice: 'Best available price',
      currentlyUnavailable: 'Currently unavailable',
      viewDetails: 'View Details',
      addToCart: 'Add to Cart',
      removed: 'Medicine removed from saved items.',
      removeError: 'Failed to remove medicine.',
      loadError: 'Failed to load saved medicines.',
      addedToCart: 'Medicine added to cart successfully.',
      addToCartError: 'Failed to add medicine to cart.',
      pharmacyUnavailable: 'No pharmacy currently has this medicine in stock.',
      confirmRemove: 'Remove from saved?',
      confirmRemoveMessage: 'This medicine will be removed from your saved list.',
    },
    addresses: {
      eyebrow: 'Delivery Locations',
      title: 'Address Book',
      subtitleOne: 'address saved',
      subtitleMany: 'addresses saved',
      addAddress: 'Add Address',
      addNew: 'Add New Address',
      editAddress: 'Edit Address',
      emptyTitle: 'No saved addresses yet',
      emptyMessage: 'Add your first delivery address to get started.',
      label: 'Address Label',
      city: 'City',
      district: 'District',
      street: 'Street',
      building: 'Building Number',
      buildingOptional: 'Building Number (Optional)',
      defaultLabel: 'Default address',
      setDefault: 'Set as default',
      defaultToggle: 'Set as my default delivery address',
      requiredError: 'Please complete all required fields.',
      loadError: 'Failed to load addresses.',
      saveError: 'Failed to save address.',
      deleteError: 'Failed to delete address.',
      defaultError: 'Failed to update the default address.',
      created: 'Address added successfully.',
      updated: 'Address updated successfully.',
      deleted: 'Address deleted successfully.',
      defaultUpdated: 'Default address updated successfully.',
      deletePrompt: 'Delete this address?',
      deleteMessage: 'This action cannot be undone.',
      placeholders: {
        title: 'Example: Home, Work, Clinic',
        city: 'Example: Riyadh',
        district: 'Example: Al Nakheel',
        street: 'Example: King Fahd Road',
        building: 'Example: 123',
      },
    },
    notifications: {
      eyebrow: 'Stay Updated',
      title: 'Notifications',
      deleteLabel: 'Delete',
      all: 'All',
      unread: 'Unread',
      markAllRead: 'Mark All as Read',
      markRead: 'Mark as Read',
      deleteAll: 'Delete All',
      emptyTitle: 'No notifications yet',
      emptyUnreadTitle: 'No unread notifications',
      emptyMessage: 'Your updates will appear here.',
      emptyUnreadMessage: 'You have read all your notifications.',
      loadError: 'Failed to load notifications.',
      markReadError: 'Failed to mark notification as read.',
      markAllReadError: 'Failed to mark all notifications as read.',
      markedAllRead: 'All notifications were marked as read.',
      deleteError: 'Failed to delete notification.',
      deleted: 'Notification deleted.',
      deletedAll: 'All notifications deleted.',
      confirmDeleteAll: 'Delete all notifications?',
      confirmDeleteAllMessage: 'This will permanently remove every notification in your list.',
      unreadCountOne: 'unread notification',
      unreadCountMany: 'unread notifications',
      types: {
        order: 'Order Update',
        message: 'New Message',
        prescription: 'Prescription Update',
        system: 'System Notification',
      },
    },
    chat: {
      title: 'Pharmacist Chat',
      subtitleCustomer: 'Choose a pharmacy and start a secure conversation with a licensed pharmacist.',
      subtitlePharmacist: 'Monitor incoming consultations and reply to customers in real time.',
      loginRequired: 'Please sign in to access chat.',
      loadError: 'Failed to load chats.',
      sendError: 'Failed to send message.',
      pharmacyNotFound: 'Selected pharmacy was not found.',
      chatCreated: 'Chat created with {{name}}.',
      createError: 'Failed to create chat.',
      whatsappUnavailable: 'WhatsApp contact is unavailable for this pharmacy.',
      openingWhatsapp: 'Opening WhatsApp...',
      selectPharmacy: 'Select a Pharmacy',
      noPharmacies: 'No pharmacies available',
      activeChannels: 'Active conversations',
      noActiveChannels: 'No active conversations yet',
      startConversation: 'Choose a pharmacy or start a new conversation to get support.',
      waitingForCustomers: 'Waiting for customer messages...',
      noMessages: 'No messages yet. Start the conversation.',
      placeholder: 'Type your message here...',
      send: 'Send',
      askOnWhatsapp: 'Continue on WhatsApp',
      startChat: 'Start Chat',
      unknownPharmacy: 'Unknown Pharmacy',
      pharmacistPortal: 'Pharmaceutical Consultation Hub',
      customerPortal: 'Secure chat with pharmacists',
      newMessageTitle: 'New Message',
      messageFrom: 'New message from {{name}}',
    },
    orders: {
      title: 'Orders',
      eyebrowCustomer: 'Order History',
      eyebrowPharmacist: 'Incoming Orders',
      loginRequired: 'Please sign in to view your orders.',
      loadError: 'Failed to load orders.',
      notFound: 'Order not found.',
      autoRefill: 'Enable smart refill reminders',
      totalAmount: 'Total amount',
      placedOn: 'Placed on {{date}}',
      customerId: 'Customer ID: {{id}}...',
      refill: 'Reorder',
      refillSuccess: 'The order items were added back to your cart.',
      refillError: 'Failed to reorder these items.',
      updateError: 'Failed to update order status.',
      updateLoading: 'Updating...',
      statusChanged: 'Order status updated to {{status}}.',
      confirm: 'Confirm',
      reject: 'Reject',
      startPreparing: 'Start Preparing',
      markReady: 'Mark Ready',
      complete: 'Complete',
      delivery: 'Home Delivery',
      pickup: 'Pickup',
      emptyTitle: 'No orders yet',
      emptyCustomer: 'Your submitted orders will appear here for tracking.',
      emptyPharmacist: 'Customer orders assigned to your pharmacy will appear here.',
      notes: 'Notes',
      statusLabels: {
        pending: 'Pending',
        confirmed: 'Confirmed',
        preparing: 'Preparing',
        ready: 'Ready for Pickup',
        out_for_delivery: 'Out for Delivery',
        completed: 'Completed',
        cancelled: 'Cancelled',
        rejected: 'Rejected',
      } as Record<OrderStatus, string>,
      notificationMessages: {
        pending: 'Your order was received successfully.',
        confirmed: 'Your order has been confirmed.',
        preparing: 'Your order is currently being prepared.',
        ready: 'Your order is ready for pickup.',
        out_for_delivery: 'Your order is out for delivery.',
        completed: 'Your order has been completed.',
        cancelled: 'Your order has been cancelled.',
        rejected: 'Your order has been rejected.',
      } as Record<OrderStatus, string>,
    },
    cart: {
      title: 'Shopping Cart',
      eyebrow: 'Ready to Checkout',
      signInTitle: 'Please sign in',
      signInMessage: 'You need to sign in to view your cart.',
      loadError: 'Failed to load your cart.',
      quantityUpdated: 'Quantity updated successfully.',
      quantityError: 'Failed to update quantity.',
      itemRemoved: 'Item removed from cart.',
      removeError: 'Failed to remove item.',
      loginWarning: 'Please sign in to continue.',
      emptyWarning: 'Your cart is currently empty.',
      missingPharmacy: 'A pharmacy must be selected before placing an order.',
      addressRequired: 'Please select a delivery address.',
      prescriptionRequired: 'A prescription is required for regulated medicines.',
      fileTooLarge: 'Prescription files must be smaller than 5 MB.',
      invalidFileType: 'Only JPG, PNG, and PDF files are allowed.',
      uploadingPrescription: 'Uploading prescription...',
      orderSuccess: 'Your order has been placed successfully.',
      checkoutError: 'Failed to place the order.',
      deliveryDetails: 'Delivery details',
      pickupDetails: 'Pickup details',
      selectAddress: 'Select delivery address',
      addAddress: 'Add Address',
      uploadPrescription: 'Upload Prescription',
      prescriptionHint: 'Upload a clear image or PDF for medicines that require a prescription.',
      subtotal: 'Subtotal',
      deliveryFee: 'Delivery Fee',
      total: 'Total',
      free: 'Free',
      processing: 'Processing...',
      placeOrder: 'Place Order',
      secure: 'Secure',
      fast: 'Fast',
      continueShopping: 'Continue Shopping',
      emptyTitle: 'Your cart is empty',
      emptyMessage: 'Explore medicines and add what you need to begin.',
      quantity: 'Quantity',
      orderType: 'Order Type',
      delivery: 'Delivery',
      pickup: 'Pickup',
      selectedPharmacy: 'Selected Pharmacy',
      cartSummary: 'Order Summary',
      regulatedMedicines: 'Prescription required items detected',
      placeholders: {
        notes: 'Add delivery or pharmacist notes if needed.',
      },
    },
    medicines: {
      eyebrow: 'Medicine Discovery',
      title: 'Medicines',
      searchPlaceholder: 'Search by brand, generic name, category, or manufacturer...',
      results: 'results',
      noResultsTitle: 'No medicines found',
      noResultsMessage: 'Try adjusting your search or filters.',
      clearFilters: 'Clear filters',
      loginRequired: 'Please sign in first.',
      saved: 'Medicine saved.',
      removed: 'Medicine removed from saved items.',
      operationFailed: 'The operation could not be completed.',
      sort: {
        relevance: 'Most relevant',
        priceLow: 'Price: Low to High',
        priceHigh: 'Price: High to Low',
        nameAz: 'Name: A - Z',
        nameZa: 'Name: Z - A'
      },
      dosageOptions: {
        all: 'All dosage forms',
        tablet: 'Tablets',
        syrup: 'Syrup',
        injection: 'Injection',
        capsule: 'Capsules',
        cream: 'Cream',
        drops: 'Drops'
      },
      ask: 'Ask',
      view: 'View',
      compareView: 'Compare Prices',
      startingFrom: 'Starting from',
      dosageFallback: 'Medicine',
      stock: {
        out: 'Out of stock',
        in: 'In stock',
        limited: 'Limited stock',
      },
    },
    medicineDetails: {
      back: 'Back',
      choosePharmacy: 'Choose Pharmacy',
      decrease: 'Decrease quantity',
      increase: 'Increase quantity',
      unavailable: 'This medicine is currently unavailable at all pharmacies.',
      addToCartSuccess: 'Medicine added to cart successfully.',
      loadError: 'Failed to load medicine details.',
      pleaseLogin: 'Please sign in first.',
      saved: 'Medicine saved.',
      unsaved: 'Medicine removed from saved items.',
      operationFailed: 'The operation could not be completed.',
      loading: 'Loading...',
      notFound: 'Item not found.',
      strength: 'Strength',
      manufacturer: 'Manufacturer',
      requiresPrescription: 'Prescription Required',
      yes: 'Yes',
      no: 'No',
      availableAt: 'Available at',
      pharmacies: 'pharmacies',
      aboutMedicine: 'About this medicine',
      usageInstructions: 'Usage instructions',
      warnings: 'Important warnings',
      priceComparison: 'Available pharmacies',
      bestPrice: 'Best price',
      cheapest: 'Cheapest',
      inStock: 'In stock',
      limitedStock: 'Limited stock',
      deliveryAvailable: 'Delivery available',
      selectedPharmacy: 'Selected pharmacy',
      quantity: 'Quantity',
      unitPrice: 'Unit price',
      totalPrice: 'Total',
      addToCart: 'Add to Cart',
      askPharmacist: 'Ask the pharmacist'
    },
  },
  ar: {
    common: {
      currencyCode: 'ر.س',
      pleaseSignIn: 'يرجى تسجيل الدخول للمتابعة.',
      loading: 'جاري التحميل...',
      browseMedicines: 'تصفح الأدوية',
      save: 'حفظ',
      cancel: 'إلغاء',
      edit: 'تعديل',
      remove: 'إزالة',
      delete: 'حذف',
      add: 'إضافة',
      confirm: 'تأكيد',
      setDefault: 'تعيين كافتراضي',
      notProvided: 'غير مضاف',
    },
    profile: {
      eyebrow: 'المركز الشخصي',
      title: 'ملفي الشخصي',
      subtitle: 'أدر معلوماتك الشخصية وتفضيلات حسابك بأمان.',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      role: 'الدور',
      roleTitle: 'صلاحيات الوصول',
      roleDescription: 'يحدد دورك الصفحات والبيانات التي يمكنك الوصول إليها. لا يمكن تغيير الدور إلا من خلال المدير.',
      signOut: 'تسجيل الخروج',
      signingOut: 'جاري تسجيل الخروج...',
      signedOut: 'تم تسجيل الخروج بنجاح.',
      signOutError: 'فشل تسجيل الخروج.',
      editProfile: 'تعديل الملف',
      fullName: 'الاسم الكامل',
      saveChanges: 'حفظ التعديلات',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح.',
      updateError: 'فشل تحديث الملف الشخصي.',
      loginRequired: 'يرجى تسجيل الدخول لعرض الملف الشخصي.',
      userId: 'معرف المستخدم',
      roleLabels: {
        admin: 'مدير',
        pharmacist: 'صيدلي',
        customer: 'عميل',
      },
    },
    saved: {
      eyebrow: 'الوصول السريع',
      title: 'الأدوية المحفوظة',
      subtitleOne: 'دواء محفوظ للوصول السريع',
      subtitleMany: 'أدوية محفوظة للوصول السريع',
      emptyTitle: 'لا توجد أدوية محفوظة بعد',
      emptyMessage: 'احفظ الأدوية للوصول إليها بسرعة لاحقًا.',
      dosageFallback: 'دواء',
      strength: 'التركيز',
      bestAvailablePrice: 'أفضل سعر متاح',
      currentlyUnavailable: 'غير متوفر حاليًا',
      viewDetails: 'عرض التفاصيل',
      addToCart: 'إضافة إلى السلة',
      removed: 'تمت إزالة الدواء من المحفوظات.',
      removeError: 'فشل إزالة الدواء من المحفوظات.',
      loadError: 'فشل تحميل الأدوية المحفوظة.',
      addedToCart: 'تمت إضافة الدواء إلى السلة بنجاح.',
      addToCartError: 'فشل إضافة الدواء إلى السلة.',
      pharmacyUnavailable: 'لا توجد صيدلية لديها هذا الدواء متوفرًا حاليًا.',
      confirmRemove: 'إزالة من المحفوظات؟',
      confirmRemoveMessage: 'سيتم إزالة هذا الدواء من قائمة المحفوظات.',
    },
    addresses: {
      eyebrow: 'عناوين التوصيل',
      title: 'إدارة العناوين',
      subtitleOne: 'عنوان محفوظ',
      subtitleMany: 'عناوين محفوظة',
      addAddress: 'إضافة عنوان',
      addNew: 'إضافة عنوان جديد',
      editAddress: 'تعديل العنوان',
      emptyTitle: 'لا توجد عناوين محفوظة بعد',
      emptyMessage: 'أضف أول عنوان توصيل للبدء.',
      label: 'اسم العنوان',
      city: 'المدينة',
      district: 'الحي',
      street: 'الشارع',
      building: 'رقم المبنى',
      buildingOptional: 'رقم المبنى (اختياري)',
      defaultLabel: 'العنوان الافتراضي',
      setDefault: 'تعيين كافتراضي',
      defaultToggle: 'تعيين هذا العنوان كعنوان التوصيل الافتراضي',
      requiredError: 'يرجى تعبئة جميع الحقول المطلوبة.',
      loadError: 'فشل تحميل العناوين.',
      saveError: 'فشل حفظ العنوان.',
      deleteError: 'فشل حذف العنوان.',
      defaultError: 'فشل تحديث العنوان الافتراضي.',
      created: 'تمت إضافة العنوان بنجاح.',
      updated: 'تم تحديث العنوان بنجاح.',
      deleted: 'تم حذف العنوان بنجاح.',
      defaultUpdated: 'تم تحديث العنوان الافتراضي بنجاح.',
      deletePrompt: 'حذف هذا العنوان؟',
      deleteMessage: 'لا يمكن التراجع عن هذا الإجراء.',
      placeholders: {
        title: 'مثال: المنزل، المكتب، العيادة',
        city: 'مثال: الرياض',
        district: 'مثال: حي النخيل',
        street: 'مثال: طريق الملك فهد',
        building: 'مثال: 123',
      },
    },
    notifications: {
      eyebrow: 'ابقَ على اطلاع',
      title: 'الإشعارات',
      deleteLabel: 'حذف',
      all: 'الكل',
      unread: 'غير المقروءة',
      markAllRead: 'تعليم الكل كمقروء',
      markRead: 'تعليم كمقروء',
      deleteAll: 'حذف الكل',
      emptyTitle: 'لا توجد إشعارات بعد',
      emptyUnreadTitle: 'لا توجد إشعارات غير مقروءة',
      emptyMessage: 'ستظهر تحديثاتك هنا.',
      emptyUnreadMessage: 'لقد قرأت جميع إشعاراتك.',
      loadError: 'فشل تحميل الإشعارات.',
      markReadError: 'فشل تعليم الإشعار كمقروء.',
      markAllReadError: 'فشل تعليم جميع الإشعارات كمقروءة.',
      markedAllRead: 'تم تعليم جميع الإشعارات كمقروءة.',
      deleteError: 'فشل حذف الإشعار.',
      deleted: 'تم حذف الإشعار.',
      deletedAll: 'تم حذف جميع الإشعارات.',
      confirmDeleteAll: 'هل تريد حذف جميع الإشعارات؟',
      confirmDeleteAllMessage: 'سيؤدي هذا إلى إزالة كل الإشعارات من قائمتك نهائيًا.',
      unreadCountOne: 'إشعار غير مقروء',
      unreadCountMany: 'إشعارات غير مقروءة',
      types: {
        order: 'تحديث الطلب',
        message: 'رسالة جديدة',
        prescription: 'تحديث الوصفة',
        system: 'إشعار النظام',
      },
    },
    chat: {
      title: 'المحادثة مع الصيدلي',
      subtitleCustomer: 'اختر صيدلية وابدأ محادثة آمنة مع صيدلي مرخص.',
      subtitlePharmacist: 'تابع استفسارات العملاء ورد عليها مباشرة.',
      loginRequired: 'يرجى تسجيل الدخول للوصول إلى المحادثات.',
      loadError: 'فشل تحميل المحادثات.',
      sendError: 'فشل إرسال الرسالة.',
      pharmacyNotFound: 'الصيدلية المحددة غير موجودة.',
      chatCreated: 'تم إنشاء محادثة مع {{name}}.',
      createError: 'فشل إنشاء المحادثة.',
      whatsappUnavailable: 'رقم واتساب غير متاح لهذه الصيدلية.',
      openingWhatsapp: 'جاري فتح واتساب...',
      selectPharmacy: 'اختر صيدلية',
      noPharmacies: 'لا توجد صيدليات متاحة',
      activeChannels: 'المحادثات النشطة',
      noActiveChannels: 'لا توجد محادثات نشطة بعد',
      startConversation: 'اختر صيدلية أو ابدأ محادثة جديدة للحصول على المساعدة.',
      waitingForCustomers: 'بانتظار رسائل العملاء...',
      noMessages: 'لا توجد رسائل بعد. ابدأ المحادثة.',
      placeholder: 'اكتب رسالتك هنا...',
      send: 'إرسال',
      askOnWhatsapp: 'المتابعة عبر واتساب',
      startChat: 'بدء المحادثة',
      unknownPharmacy: 'صيدلية غير معروفة',
      pharmacistPortal: 'بوابة الاستشارة الصيدلية',
      customerPortal: 'محادثة آمنة مع الصيادلة',
      newMessageTitle: 'رسالة جديدة',
      messageFrom: 'رسالة جديدة من {{name}}',
    },
    orders: {
      title: 'الطلبات',
      eyebrowCustomer: 'سجل الطلبات',
      eyebrowPharmacist: 'الطلبات الواردة',
      loginRequired: 'يرجى تسجيل الدخول لعرض طلباتك.',
      loadError: 'فشل تحميل الطلبات.',
      notFound: 'الطلب غير موجود.',
      autoRefill: 'تفعيل تذكيرات إعادة الطلب الذكية',
      totalAmount: 'القيمة الإجمالية',
      placedOn: 'تم الطلب في {{date}}',
      customerId: 'معرف العميل: {{id}}...',
      refill: 'إعادة الطلب',
      refillSuccess: 'تمت إضافة عناصر الطلب إلى السلة مرة أخرى.',
      refillError: 'فشل إعادة طلب هذه العناصر.',
      updateError: 'فشل تحديث حالة الطلب.',
      updateLoading: 'جاري التحديث...',
      statusChanged: 'تم تحديث حالة الطلب إلى {{status}}.',
      confirm: 'تأكيد',
      reject: 'رفض',
      startPreparing: 'بدء التحضير',
      markReady: 'تعليم كجاهز',
      complete: 'إكمال',
      delivery: 'توصيل منزلي',
      pickup: 'استلام',
      emptyTitle: 'لا توجد طلبات بعد',
      emptyCustomer: 'ستظهر طلباتك هنا عند تقديمها للمتابعة.',
      emptyPharmacist: 'ستظهر هنا الطلبات المرتبطة بصيدليتك.',
      notes: 'ملاحظات',
      statusLabels: {
        pending: 'قيد الانتظار',
        confirmed: 'مؤكد',
        preparing: 'قيد التحضير',
        ready: 'جاهز للاستلام',
        out_for_delivery: 'قيد التوصيل',
        completed: 'مكتمل',
        cancelled: 'ملغي',
        rejected: 'مرفوض',
      } as Record<OrderStatus, string>,
      notificationMessages: {
        pending: 'تم استلام طلبك بنجاح.',
        confirmed: 'تم تأكيد طلبك.',
        preparing: 'يجري الآن تحضير طلبك.',
        ready: 'طلبك جاهز للاستلام.',
        out_for_delivery: 'طلبك خرج للتوصيل.',
        completed: 'تم إكمال طلبك.',
        cancelled: 'تم إلغاء طلبك.',
        rejected: 'تم رفض طلبك.',
      } as Record<OrderStatus, string>,
    },
    cart: {
      title: 'سلة التسوق',
      eyebrow: 'جاهز لإتمام الطلب',
      signInTitle: 'يرجى تسجيل الدخول',
      signInMessage: 'يجب تسجيل الدخول لعرض السلة.',
      loadError: 'فشل تحميل السلة.',
      quantityUpdated: 'تم تحديث الكمية بنجاح.',
      quantityError: 'فشل تحديث الكمية.',
      itemRemoved: 'تمت إزالة العنصر من السلة.',
      removeError: 'فشل إزالة العنصر.',
      loginWarning: 'يرجى تسجيل الدخول للمتابعة.',
      emptyWarning: 'سلتك فارغة حاليًا.',
      missingPharmacy: 'يجب اختيار صيدلية قبل تأكيد الطلب.',
      addressRequired: 'يرجى اختيار عنوان التوصيل.',
      prescriptionRequired: 'الوصفة الطبية مطلوبة للأدوية المنظمة.',
      fileTooLarge: 'يجب أن يكون ملف الوصفة أقل من 5 ميجابايت.',
      invalidFileType: 'يسمح فقط بملفات JPG وPNG وPDF.',
      uploadingPrescription: 'جاري رفع الوصفة...',
      orderSuccess: 'تم تقديم الطلب بنجاح.',
      checkoutError: 'فشل تقديم الطلب.',
      deliveryDetails: 'تفاصيل التوصيل',
      pickupDetails: 'تفاصيل الاستلام',
      selectAddress: 'اختر عنوان التوصيل',
      addAddress: 'إضافة عنوان',
      uploadPrescription: 'رفع الوصفة الطبية',
      prescriptionHint: 'حمّل صورة واضحة أو ملف PDF للأدوية التي تتطلب وصفة.',
      subtotal: 'المجموع الفرعي',
      deliveryFee: 'رسوم التوصيل',
      total: 'الإجمالي',
      free: 'مجاني',
      processing: 'جاري المعالجة...',
      placeOrder: 'تأكيد الطلب',
      secure: 'آمن',
      fast: 'سريع',
      continueShopping: 'متابعة التسوق',
      emptyTitle: 'سلتك فارغة',
      emptyMessage: 'تصفح الأدوية وأضف ما تحتاجه للبدء.',
      quantity: 'الكمية',
      orderType: 'نوع الطلب',
      delivery: 'توصيل',
      pickup: 'استلام',
      selectedPharmacy: 'الصيدلية المختارة',
      cartSummary: 'ملخص الطلب',
      regulatedMedicines: 'هناك عناصر تتطلب وصفة طبية',
      placeholders: {
        notes: 'أضف ملاحظات التوصيل أو ملاحظات للصيدلي إن لزم الأمر.',
      },
    },
    medicines: {
      eyebrow: 'اكتشاف الأدوية',
      title: 'الأدوية',
      searchPlaceholder: 'ابحث بالاسم التجاري أو العلمي أو الشركة المصنعة...',
      results: 'نتيجة',
      noResultsTitle: 'لم يتم العثور على أدوية',
      noResultsMessage: 'حاول تعديل البحث أو الفلاتر.',
      clearFilters: 'مسح الفلاتر',
      loginRequired: 'يرجى تسجيل الدخول أولاً.',
      saved: 'تم حفظ الدواء.',
      removed: 'تمت إزالة الدواء من المحفوظات.',
      operationFailed: 'تعذر تنفيذ العملية.',
      sort: {
        relevance: 'الأكثر صلة',
        priceLow: 'السعر: من الأقل إلى الأعلى',
        priceHigh: 'السعر: من الأعلى إلى الأقل',
        nameAz: 'الاسم: أ - ي',
        nameZa: 'الاسم: ي - أ'
      },
      dosageOptions: {
        all: 'جميع الأشكال',
        tablet: 'أقراص',
        syrup: 'شراب',
        injection: 'حقن',
        capsule: 'كبسولات',
        cream: 'كريم',
        drops: 'قطرات'
      },
      ask: 'اسأل',
      view: 'عرض',
      compareView: 'قارن الأسعار',
      startingFrom: 'يبدأ من',
      dosageFallback: 'دواء',
      stock: {
        out: 'غير متوفر',
        in: 'متوفر',
        limited: 'كمية محدودة',
      },
    },
    medicineDetails: {
      back: 'رجوع',
      choosePharmacy: 'اختر الصيدلية',
      decrease: 'تقليل الكمية',
      increase: 'زيادة الكمية',
      unavailable: 'هذا الدواء غير متوفر حاليًا في جميع الصيدليات.',
      addToCartSuccess: 'تمت إضافة الدواء إلى السلة بنجاح.',
      loadError: 'فشل تحميل تفاصيل الدواء.',
      pleaseLogin: 'يرجى تسجيل الدخول أولاً.',
      saved: 'تم حفظ الدواء.',
      unsaved: 'تمت إزالة الدواء من المحفوظات.',
      operationFailed: 'تعذر تنفيذ العملية.',
      loading: 'جاري التحميل...',
      notFound: 'العنصر غير موجود.',
      strength: 'التركيز',
      manufacturer: 'الشركة المصنعة',
      requiresPrescription: 'يتطلب وصفة',
      yes: 'نعم',
      no: 'لا',
      availableAt: 'متوفر في',
      pharmacies: 'صيدليات',
      aboutMedicine: 'عن هذا الدواء',
      usageInstructions: 'تعليمات الاستخدام',
      warnings: 'تحذيرات مهمة',
      priceComparison: 'الصيدليات المتاحة',
      bestPrice: 'أفضل سعر',
      cheapest: 'الأرخص',
      inStock: 'متوفر',
      limitedStock: 'كمية محدودة',
      deliveryAvailable: 'التوصيل متاح',
      selectedPharmacy: 'الصيدلية المختارة',
      quantity: 'الكمية',
      unitPrice: 'سعر الوحدة',
      totalPrice: 'الإجمالي',
      addToCart: 'إضافة إلى السلة',
      askPharmacist: 'اسأل الصيدلي'
    },
  },
} as const;
