/**
 * Professional Healthcare Platform Terminology
 * Arabic labels for consistent UX writing.
 * App name intentionally remains MediSmart.
 */

export const TERMINOLOGY = {
  APP_NAME: 'MediSmart',
  APP_TAGLINE: 'شريكك الموثوق في خدمات الصيدلية',

  ROLES: {
    CUSTOMER: 'عميل',
    PHARMACIST: 'صيدلي',
    ADMIN: 'مدير',
  },

  NAV: {
    HOME: 'الرئيسية',
    MEDICINES: 'الأدوية',
    ORDERS: 'الطلبات',
    CHAT: 'المحادثة مع الصيدلي',
    DASHBOARD: 'لوحة التحكم',
    INVENTORY: 'المخزون',
    USERS: 'المستخدمون',
    PHARMACIES: 'الصيدليات',
    CATEGORIES: 'الفئات',
    REPORTS: 'التقارير',
    PROFILE: 'ملفي الشخصي',
    SIGN_IN: 'تسجيل الدخول',
    SIGN_OUT: 'تسجيل الخروج',
    GET_STARTED: 'ابدأ الآن',
  },

  CART: {
    TITLE: 'سلة التسوق',
    EMPTY_STATE: 'سلتك فارغة',
    EMPTY_MESSAGE: 'أضف أدوية للبدء',
    ADD_TO_CART: 'إضافة إلى السلة',
    REMOVE_FROM_CART: 'إزالة من السلة',
    UPDATE_QUANTITY: 'تحديث الكمية',
    PROCEED_TO_CHECKOUT: 'إتمام الطلب',
    CONTINUE_SHOPPING: 'متابعة التسوق',
    SUBTOTAL: 'المجموع الفرعي',
    DELIVERY_FEE: 'رسوم التوصيل',
    TOTAL: 'الإجمالي',
    ITEM_COUNT: 'العناصر',
  },

  ORDERS: {
    TITLE: 'طلباتي',
    EMPTY_STATE: 'لا توجد طلبات بعد',
    EMPTY_MESSAGE: 'ابدأ بتصفح الأدوية',
    ORDER_NUMBER: 'رقم الطلب',
    ORDER_DATE: 'تاريخ الطلب',
    ORDER_STATUS: 'الحالة',
    TOTAL_AMOUNT: 'المبلغ الإجمالي',
    DELIVERY_TYPE: 'نوع التسليم',
    PICKUP: 'استلام',
    DELIVERY: 'توصيل',
    REFILL: 'إعادة الطلب',
    REFILL_TOOLTIP: 'إعادة طلب الأدوية نفسها',
    VIEW_DETAILS: 'عرض التفاصيل',
    TRACK_ORDER: 'تتبع الطلب',
  },

  ORDER_STATUS: {
    PENDING: 'قيد الانتظار',
    PENDING_DESC: 'بانتظار التأكيد',
    CONFIRMED: 'مؤكد',
    CONFIRMED_DESC: 'تم تأكيد الطلب',
    PREPARING: 'قيد التحضير',
    PREPARING_DESC: 'يتم تحضيره',
    READY: 'جاهز للاستلام',
    READY_DESC: 'جاهز للاستلام',
    SHIPPED: 'تم الشحن',
    SHIPPED_DESC: 'في الطريق',
    COMPLETED: 'مكتمل',
    COMPLETED_DESC: 'تم إكمال الطلب',
    CANCELLED: 'ملغي',
    CANCELLED_DESC: 'تم إلغاء الطلب',
  },

  MEDICINES: {
    TITLE: 'الأدوية',
    SEARCH_PLACEHOLDER: 'ابحث بالاسم التجاري أو العلمي أو الشركة المصنعة أو الفئة...',
    FILTER_DOSAGE: 'تصفية حسب الشكل الدوائي',
    ALL_DOSAGE_FORMS: 'جميع الأشكال الدوائية',
    SORT_BY: 'ترتيب حسب',
    SORT_RELEVANCE: 'الأكثر صلة',
    SORT_PRICE_LOW: 'السعر: من الأقل إلى الأعلى',
    SORT_PRICE_HIGH: 'السعر: من الأعلى إلى الأقل',
    SORT_NAME_AZ: 'الاسم: أ - ي',
    SORT_NAME_ZA: 'الاسم: ي - أ',
    BRAND_NAME: 'الاسم التجاري',
    GENERIC_NAME: 'الاسم العلمي',
    DOSAGE_FORM: 'الشكل الدوائي',
    STRENGTH: 'التركيز',
    MANUFACTURER: 'الشركة المصنعة',
    DESCRIPTION: 'الوصف',
    USAGE_INSTRUCTIONS: 'تعليمات الاستخدام',
    WARNINGS: 'تحذيرات مهمة',
    REQUIRES_PRESCRIPTION: 'يتطلب وصفة طبية',
    YES: 'نعم',
    NO: 'لا',
    AVAILABLE_AT: 'متوفر في',
    PHARMACIES: 'صيدليات',
    NO_RESULTS: 'لم يتم العثور على أدوية',
    NO_RESULTS_MESSAGE: 'حاول تعديل البحث أو الفلاتر',
    CLEAR_FILTERS: 'مسح البحث',
    LOADING: 'جاري تحميل الأدوية...',
    RESULTS_COUNT: 'نتائج',
  },

  MEDICINE_DETAILS: {
    PRICE_COMPARISON: 'الصيدليات المتاحة',
    BEST_PRICE: 'أفضل سعر',
    CHEAPEST_OPTION: 'الأرخص',
    SELECTED_PHARMACY: 'الصيدلية المختارة',
    QUANTITY: 'الكمية',
    UNIT_PRICE: 'سعر الوحدة',
    TOTAL_PRICE: 'الإجمالي',
    IN_STOCK: 'متوفر',
    LIMITED_STOCK: 'كمية محدودة',
    OUT_OF_STOCK: 'غير متوفر',
    SAVE_MEDICINE: 'حفظ لاحقاً',
    SAVED: 'محفوظ',
    UNSAVE: 'إزالة من المحفوظات',
    ASK_PHARMACIST: 'اسأل الصيدلي',
    UNAVAILABLE: 'غير متوفر حالياً في جميع الصيدليات',
    DELIVERY_AVAILABLE: 'التوصيل متاح',
    ABOUT_MEDICINE: 'عن هذا الدواء',
    BACK_TO_MEDICINES: 'العودة إلى الأدوية',
  },

  SAVED_MEDICINES: {
    TITLE: 'الأدوية المحفوظة',
    EMPTY_STATE: 'لا توجد أدوية محفوظة',
    EMPTY_MESSAGE: 'احفظ الأدوية للوصول السريع لاحقاً',
    BROWSE_MEDICINES: 'تصفح الأدوية',
    SAVED_COUNT: 'محفوظة للوصول السريع',
  },

  ADDRESSES: {
    TITLE: 'عناوين التوصيل',
    EMPTY_STATE: 'لا توجد عناوين محفوظة',
    EMPTY_MESSAGE: 'أضف عنوان التوصيل الأول',
    ADD_ADDRESS: 'إضافة عنوان',
    EDIT_ADDRESS: 'تعديل العنوان',
    DELETE_ADDRESS: 'حذف العنوان',
    SET_DEFAULT: 'تعيين كافتراضي',
    DEFAULT_ADDRESS: 'العنوان الافتراضي',
    ADDRESS_LABEL: 'اسم العنوان',
    CITY: 'المدينة',
    DISTRICT: 'الحي',
    STREET: 'الشارع',
    BUILDING_NUMBER: 'رقم المبنى',
    OPTIONAL: 'اختياري',
    CONFIRM_DELETE: 'هل أنت متأكد من حذف هذا العنوان؟',
    ADDRESS_SAVED: 'تم حفظ العنوان بنجاح',
    ADDRESS_UPDATED: 'تم تحديث العنوان بنجاح',
    ADDRESS_DELETED: 'تم حذف العنوان بنجاح',
  },

  NOTIFICATIONS: {
    TITLE: 'الإشعارات',
    EMPTY_STATE: 'لا توجد إشعارات',
    EMPTY_MESSAGE: 'أنت على اطلاع بكل شيء',
    UNREAD: 'غير مقروء',
    MARK_AS_READ: 'تعليم كمقروء',
    MARK_ALL_READ: 'تعليم الكل كمقروء',
    DELETE: 'حذف',
    DELETE_ALL: 'حذف جميع الإشعارات',
    CONFIRM_DELETE_ALL: 'هل تريد حذف جميع الإشعارات؟',
    ORDER_NOTIFICATION: 'تحديث الطلب',
    MESSAGE_NOTIFICATION: 'رسالة جديدة',
    PRESCRIPTION_NOTIFICATION: 'تحديث الوصفة',
    SYSTEM_NOTIFICATION: 'إشعار النظام',
  },

  CHAT: {
    TITLE: 'المحادثة مع الصيدلي',
    EMPTY_STATE: 'لا توجد محادثات نشطة',
    EMPTY_MESSAGE: 'ابدأ محادثة مع الصيدلي',
    SELECT_PHARMACY: 'اختر صيدلية',
    START_CHAT: 'بدء محادثة',
    SEND_MESSAGE: 'إرسال الرسالة',
    TYPE_MESSAGE: 'اكتب رسالتك...',
    PHARMACIST: 'صيدلي',
    ONLINE: 'متصل',
    OFFLINE: 'غير متصل',
    ESCALATE_TO_WHATSAPP: 'متابعة عبر واتساب',
  },

  PROFILE: {
    TITLE: 'ملفي الشخصي',
    PERSONAL_INFO: 'المعلومات الشخصية',
    FULL_NAME: 'الاسم الكامل',
    EMAIL: 'البريد الإلكتروني',
    PHONE: 'رقم الهاتف',
    ROLE: 'الدور',
    MEMBER_SINCE: 'عضو منذ',
    EDIT_PROFILE: 'تعديل الملف',
    CHANGE_PASSWORD: 'تغيير كلمة المرور',
    PREFERENCES: 'التفضيلات',
    LANGUAGE: 'اللغة',
    NOTIFICATIONS_SETTINGS: 'إعدادات الإشعارات',
    PRIVACY: 'الخصوصية والأمان',
    SIGN_OUT: 'تسجيل الخروج',
    CONFIRM_SIGN_OUT: 'هل أنت متأكد من تسجيل الخروج؟',
  },

  PHARMACIST: {
    TITLE: 'لوحة تحكم الصيدلي',
    ADD_MEDICINE: 'إضافة دواء',
    EDIT_MEDICINE: 'تعديل الدواء',
    DELETE_MEDICINE: 'حذف الدواء',
    INVENTORY: 'إدارة المخزون',
    INCOMING_ORDERS: 'الطلبات الواردة',
    CONFIRM_ORDER: 'تأكيد الطلب',
    REJECT_ORDER: 'رفض الطلب',
    START_PREPARING: 'بدء التحضير',
    MARK_READY: 'تعليم كجاهز',
    COMPLETE_ORDER: 'إتمام الطلب',
    MEDICINE_ADDED: 'تمت إضافة الدواء بنجاح',
    MEDICINE_UPDATED: 'تم تحديث الدواء بنجاح',
    MEDICINE_DELETED: 'تم حذف الدواء بنجاح',
    ORDER_CONFIRMED: 'تم تأكيد الطلب',
    ORDER_REJECTED: 'تم رفض الطلب',
  },

  ADMIN: {
    TITLE: 'لوحة تحكم المدير',
    MANAGE_CATEGORIES: 'إدارة الفئات',
    ADD_CATEGORY: 'إضافة فئة',
    EDIT_CATEGORY: 'تعديل الفئة',
    DELETE_CATEGORY: 'حذف الفئة',
    CATEGORY_ADDED: 'تمت إضافة الفئة بنجاح',
    CATEGORY_UPDATED: 'تم تحديث الفئة بنجاح',
    CATEGORY_DELETED: 'تم حذف الفئة بنجاح',
    REPORTS: 'التقارير والتحليلات',
    TOTAL_USERS: 'إجمالي المستخدمين',
    TOTAL_PHARMACIES: 'إجمالي الصيدليات',
    TOTAL_MEDICINES: 'إجمالي الأدوية',
    TOTAL_ORDERS: 'إجمالي الطلبات',
    TOTAL_REVENUE: 'إجمالي الإيرادات',
    PENDING_ORDERS: 'الطلبات المعلقة',
    LOW_STOCK_ITEMS: 'العناصر منخفضة المخزون',
  },

  FORMS: {
    REQUIRED_FIELD: 'هذا الحقل مطلوب',
    INVALID_EMAIL: 'يرجى إدخال بريد إلكتروني صحيح',
    PASSWORD_MISMATCH: 'كلمتا المرور غير متطابقتين',
    SUBMIT: 'إرسال',
    CANCEL: 'إلغاء',
    SAVE: 'حفظ',
    UPDATE: 'تحديث',
    DELETE: 'حذف',
    CLOSE: 'إغلاق',
    LOADING: 'جاري التحميل...',
    SAVING: 'جاري الحفظ...',
    DELETING: 'جاري الحذف...',
  },

  MESSAGES: {
    SUCCESS: 'نجاح',
    ERROR: 'خطأ',
    WARNING: 'تحذير',
    INFO: 'معلومة',
    PLEASE_LOGIN: 'الرجاء تسجيل الدخول للمتابعة',
    PLEASE_FILL_REQUIRED: 'يرجى تعبئة جميع الحقول المطلوبة',
    OPERATION_FAILED: 'فشلت العملية. حاول مرة أخرى.',
    OPERATION_SUCCESS: 'تمت العملية بنجاح',
    NETWORK_ERROR: 'خطأ في الشبكة. تحقق من اتصالك.',
    UNAUTHORIZED: 'ليس لديك صلاحية لتنفيذ هذا الإجراء',
    NOT_FOUND: 'العنصر المطلوب غير موجود',
  },

  A11Y: {
    SKIP_TO_CONTENT: 'تجاوز إلى المحتوى الرئيسي',
    MAIN_NAVIGATION: 'التنقل الرئيسي',
    SEARCH_MEDICINES: 'البحث عن الأدوية',
    FILTER_OPTIONS: 'خيارات التصفية',
    PRODUCT_GRID: 'شبكة المنتجات',
    PAGINATION: 'ترقيم الصفحات',
    CLOSE_MENU: 'إغلاق القائمة',
    OPEN_MENU: 'فتح القائمة',
    LOADING_INDICATOR: 'جاري التحميل',
    ERROR_ALERT: 'خطأ',
    SUCCESS_ALERT: 'نجاح',
  },
};

export default TERMINOLOGY;
